export  const POSTS = [
  {
    id: 1,
    user: 'Amy Losartan',
    title: 'Pothole on Panama Street',
    profile: require('../assets/addedAssets/profiles/amyLosartan.jpg'),
    picture: require('../assets/addedAssets/images/potholes.jpg'),
    description: 'There is a huge pothole on the corner of Panama and Lasuen that needs fixing! ',
    location: 'Palo Alto, CA',
    timestamp: '2 hr',
    likes: 15,
    comments: 3,
    isEndorsed: true,
  },

  {
    id: 2,
    user: 'Samuel James',
    title: 'We need more park benches',
    profile: require('../assets/addedAssets/profiles/samuelJames.jpg'),
    picture: require('../assets/addedAssets/images/parkBench.jpg'),
    description: 'The benches at Palo Alto Park are all beat up and broken😡 ',
    location: 'Alameda, CA',
    timestamp: '4 hr',
    likes: 20,
    comments: 5,
    isEndorsed: false,
  }, 

  {
    id: 3,
    user: 'Matthew Liu',
    title: 'Cal Train Tickets are so expensive!',
    profile: require('../assets/addedAssets/profiles/matthewLiu.jpg'),
    picture: require('../assets/addedAssets/images/caltrainTicket.jpg'),
    description: 'The Cal Train Tickets are ridiculously expensive!  I wish there was a cheaper option. ',
    location: 'Berkeley, CA',
    timestamp: '30 min ',
    likes: 200,
    comments: 25,
    isEndorsed: false,
  },

  {
    id: 4,
    user: 'Patricia Humphrey',
    title: 'Cal Train Tickets are so expensive!',
    profile: require('../assets/addedAssets/profiles/patriciaHumphrey.jpg'),
    picture: require('../assets/addedAssets/images/boxOfBooks.jpg'),
    description: 'Calling all book lovers!  Palo Alto High is having a book drive for the rest of this month! ',
    location: 'Palo Alto, CA',
    timestamp: '1 day',
    likes: 75,
    comments: 30,
    isEndorsed: true,
  },

  {
    id: 5,
    user: 'Wanye Gorgalo',
    title: 'Too many bikes',
    profile: require('../assets/addedAssets/profiles/wanyeGorgalo.jpg'),
    picture: null,
    description: 'There are too many bikes on the sidewalk of Campus Drive, I was almost hit 3 times today!! ',
    location: 'Stanford, CA',
    timestamp: '2 days',
    likes: 60,
    comments: 9,
    isEndorsed: false,
  },
]
